version: "3"

services: 
    app1:
        container_name: crashnode
        restart: always
        build: .
        ports:
            - "3000:3000"
            - "8000:8000"
        volumes: 
            - .:/usr/src/app
    